#!/usr/bin/env sh
# shellcheck shell=sh
set -eu

: "${HOME:?HOME must be set}"

require_commands() {
  missing=
  for cmd; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
      printf 'error: missing bootstrap prerequisite: %s\n' "$cmd" >&2
      missing=1
    fi
  done
  [ -z "${missing:-}" ] || exit 1
}

# Map the host names reported by `uname` to Zig's release target names. Keeping
# this mapping here avoids needing a working Zig binary before we have finished
# installing the pinned bootstrap Zig.
zig_target() {
  os=$1
  arch=$2
  case "$os:$arch" in
  Darwin:arm64) printf '%s\n' "aarch64-macos" ;;
  Linux:aarch64 | Linux:arm64) printf '%s\n' "aarch64-linux" ;;
  Linux:x86_64) printf '%s\n' "x86_64-linux" ;;
  *)
    printf 'error: unsupported Zig bootstrap platform: %s %s\n' "$os" "$arch" >&2
    return 1
    ;;
  esac
}

zig_download_info() {
  version=$1
  target=$2
  artifacts_file=${BOOTSTRAP_ZIG_ARTIFACTS:-"$script_dir/zig-artifacts.tsv"}

  # The artifact manifest is intentionally a tiny whitespace-delimited table:
  # version, target, URL, sha256. POSIX `read` gives us enough structure here,
  # and using only shell builtins keeps the pre-Zig bootstrap dependency set
  # small on fresh machines.
  while read -r artifact_version artifact_target artifact_url artifact_sha _; do
    case "${artifact_version:-}" in
    '' | '#'*)
      continue
      ;;
    esac

    if [ "$artifact_version" = "$version" ] && [ "$artifact_target" = "$target" ]; then
      printf '%s\n%s\n' "$artifact_url" "$artifact_sha"
      return 0
    fi
  done <"$artifacts_file"

  printf 'error: unsupported pinned Zig bootstrap artifact: %s %s\n' "$version" "$target" >&2
  return 1
}

zig_bootstrap_version() {
  artifacts_file=${BOOTSTRAP_ZIG_ARTIFACTS:-"$script_dir/zig-artifacts.tsv"}

  while read -r artifact_version _; do
    case "${artifact_version:-}" in
    '' | '#'*)
      continue
      ;;
    esac

    printf '%s\n' "$artifact_version"
    return 0
  done <"$artifacts_file"

  printf 'error: no Zig bootstrap artifacts found in %s\n' "$artifacts_file" >&2
  return 1
}

hash_file() {
  file=$1
  if command -v sha256sum >/dev/null 2>&1; then
    hash_output=$(sha256sum "$file") || return 1
  elif command -v shasum >/dev/null 2>&1; then
    hash_output=$(shasum -a 256 "$file") || return 1
  elif command -v openssl >/dev/null 2>&1; then
    hash_output=$(openssl dgst -sha256 -r "$file") || return 1
  else
    printf 'error: missing SHA-256 checker: install sha256sum, shasum, or openssl\n' >&2
    return 1
  fi
  printf '%s\n' "${hash_output%% *}"
}

verify_sha256() {
  expected=$1
  file=$2
  actual=$(hash_file "$file")
  if [ "$actual" != "$expected" ]; then
    printf 'error: checksum mismatch for %s\n' "$file" >&2
    printf 'error: expected %s\n' "$expected" >&2
    printf 'error: actual   %s\n' "$actual" >&2
    return 1
  fi
}

ensure_shell_path() {
  zshenv="${HOME}/.zshenv"
  marker="nix-dotfiles bootstrap PATH"

  if [ -f "$zshenv" ] && grep -F "$marker" "$zshenv" >/dev/null 2>&1; then
    return 0
  fi

  {
    if [ -s "$zshenv" ]; then
      printf '\n'
    fi
    printf '# %s\n' "$marker"
    printf 'typeset -U path PATH 2>/dev/null || true\n'
    printf 'case ":${PATH}:" in *":${HOME}/.local/bin:"*) ;; *) PATH="${HOME}/.local/bin:${PATH}" ;; esac\n'
    printf 'export PATH\n'
  } >>"$zshenv"
}

ensure_chezmoi_config() {
  config_home="${XDG_CONFIG_HOME:-"$HOME/.config"}"
  config_dir="$config_home/chezmoi"
  config_file="$config_dir/chezmoi.toml"
  source_dir="$repo_dir/dotfiles"

  mkdir -p "$config_dir"
  if [ -f "$config_file" ]; then
    if ! grep -E '^[[:space:]]*sourceDir[[:space:]]*=' "$config_file" >/dev/null 2>&1; then
      printf '\nsourceDir = "%s"\n' "$source_dir" >>"$config_file"
    fi
    if ! grep -E '^[[:space:]]*\[secret\]' "$config_file" >/dev/null 2>&1; then
      printf '\n[secret]\ncommand = "sops"\nargs = ["--decrypt"]\n' >>"$config_file"
    fi
    return 0
  fi

  printf 'sourceDir = "%s"\n\n[secret]\ncommand = "sops"\nargs = ["--decrypt"]\n' "$source_dir" >"$config_file"
}

zig_satisfies_bootstrap() {
  [ -x "$local_bin/zig" ] || return 1
  actual=$("$local_bin/zig" version 2>/dev/null) || return 1
  [ "$actual" = "$zig_min" ]
}

install_bootstrap_zig() {
  os="$(uname -s)"
  arch="$(uname -m)"
  target="$(zig_target "$os" "$arch")"
  # `zig_download_info` prints exactly URL and checksum. Splitting its output is
  # safe because both fields are generated by our pinned TSV manifest and never
  # contain shell whitespace.
  download_info=$(zig_download_info "$zig_min" "$target") || return 1
  newline='
'
  url=${download_info%%"$newline"*}
  shasum=${download_info#*"$newline"}

  zig_dir="$local_opt/zig/$zig_min"
  zig_parent="$local_opt/zig"
  zig_tmp_dir="$zig_parent/.${target}-${zig_min}.tmp.$$"
  zig_download_tmp=$(mktemp -d "${TMPDIR:-/tmp}/zig-bootstrap.XXXXXX")
  zig_archive="$zig_download_tmp/zig.tar.xz"

  mkdir -p "$zig_parent"
  rm -rf "$zig_tmp_dir"
  mkdir -p "$zig_tmp_dir"

  # Bootstrap Zig is the root of trust for the rest of this script. Download to
  # a throwaway directory, verify the pinned hash, and only then move it into the
  # stable install location.
  curl -fsSL "$url" -o "$zig_archive"
  verify_sha256 "$shasum" "$zig_archive"
  tar -xJf "$zig_archive" -C "$zig_tmp_dir" --strip-components=1
  chmod +x "$zig_tmp_dir/zig"
  if [ "$("$zig_tmp_dir/zig" version)" != "$zig_min" ]; then
    printf 'error: downloaded Zig did not report expected version %s\n' "$zig_min" >&2
    return 1
  fi

  rm -rf "$zig_dir"
  mv "$zig_tmp_dir" "$zig_dir"
  zig_tmp_dir=
  rm -f "$local_bin/zig"
  ln -s "$zig_dir/zig" "$local_bin/zig"
}

cleanup() {
  [ -z "${zig_tmp_dir:-}" ] || rm -rf "$zig_tmp_dir"
  [ -z "${zig_download_tmp:-}" ] || rm -rf "$zig_download_tmp"
}

require_commands curl tar uname mkdir ln chmod rm mktemp mv dirname
trap cleanup EXIT HUP INT TERM

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH='' cd -- "$script_dir/.." && pwd)
local_bin="${HOME}/.local/bin"
local_opt="${HOME}/.local/opt"
mkdir -p "$local_bin" "$local_opt"
ensure_shell_path
ensure_chezmoi_config

zig_min="${BOOTSTRAP_ZIG_VERSION:-$(zig_bootstrap_version)}"

export PATH="$local_bin:$PATH"

# From here on the heavier logic lives in Zig. The shell script only guarantees
# that the exact bootstrap Zig exists and is first on PATH.
if ! zig_satisfies_bootstrap; then
  install_bootstrap_zig
fi

BOOTSTRAP_REPO_DIR="$repo_dir" zig run \
  --dep bootstrap --dep common -Mroot="$script_dir/dev_tools/main.zig" \
  --dep common -Mbootstrap="$repo_dir/lib/zig/bootstrap/root.zig" \
  -Mcommon="$repo_dir/lib/zig/common/root.zig" \
  -- install
