---
- name: Install Jujutsu from upstream release
  ansible.builtin.script:
    cmd: install-jj.sh "{{ dotfiles_cache_dir }}/jj" "{{ dotfiles_bin_dir }}"
  register: ecosystem_jj_install
  changed_when: "'installed ' in ecosystem_jj_install.stdout"
  when: common_system in ['Darwin', 'Linux']
  tags:
    - ecosystem
    - jj
    - releases

- name: Install duf from upstream release
  ansible.builtin.script:
    cmd: install-duf.sh "{{ dotfiles_cache_dir }}/duf" "{{ dotfiles_bin_dir }}"
  register: ecosystem_duf_install
  changed_when: "'installed ' in ecosystem_duf_install.stdout"
  when: common_system in ['Darwin', 'Linux']
  tags:
    - ecosystem
    - duf
    - releases

- name: Install cargo-binstall from upstream release
  ansible.builtin.script:
    cmd: install-cargo-binstall.sh "{{ dotfiles_cache_dir }}/cargo-binstall" "{{ dotfiles_home_dir }}/.cargo/bin"
  register: ecosystem_cargo_binstall_install
  changed_when: "'installed ' in ecosystem_cargo_binstall_install.stdout"
  when: common_system in ['Darwin', 'Linux']
  tags:
    - ecosystem
    - binstall
    - releases
