x-dotfiles-cache-from: &dotfiles-cache-from
  - type=local,src=.docker-cache

x-dotfiles-cache-to: &dotfiles-cache-to
  - type=local,dest=.docker-cache,mode=max

x-dotfiles-build: &dotfiles-build
  context: .
  dockerfile: Dockerfile
  pull: true
  target: dotfiles-test
  args:
    TEST_USER: dotfiles
    TEST_UID: 1000
    TEST_GID: 1000
  cache_from: *dotfiles-cache-from
  cache_to: *dotfiles-cache-to

x-dotfiles-service: &dotfiles-service
  init: true
  platform: linux/amd64
  stdin_open: true
  tty: true
  working_dir: /home/dotfiles
  command:
    - ansible-playbook
    - --version

services:
  alpine:
    <<: *dotfiles-service
    image: nix-dotfiles:alpine-test
    build:
      <<: *dotfiles-build
      args:
        TEST_USER: dotfiles
        TEST_UID: 1000
        TEST_GID: 1000
        BASE_IMAGE: alpine:3.23

  fedora-44:
    <<: *dotfiles-service
    image: nix-dotfiles:fedora-44-test
    build:
      <<: *dotfiles-build
      args:
        TEST_USER: dotfiles
        TEST_UID: 1000
        TEST_GID: 1000
        BASE_IMAGE: fedora:44

  alpine-shell:
    <<: *dotfiles-service
    profiles:
      - shell
    image: nix-dotfiles:alpine-test
    build:
      <<: *dotfiles-build
      args:
        TEST_USER: dotfiles
        TEST_UID: 1000
        TEST_GID: 1000
        BASE_IMAGE: alpine:3.23
    working_dir: /workspace/nix-dotfiles
    command:
      - zsh
      - -l

  fedora-44-shell:
    <<: *dotfiles-service
    profiles:
      - shell
    image: nix-dotfiles:fedora-44-test
    build:
      <<: *dotfiles-build
      args:
        TEST_USER: dotfiles
        TEST_UID: 1000
        TEST_GID: 1000
        BASE_IMAGE: fedora:44
    working_dir: /workspace/nix-dotfiles
    command:
      - zsh
      - -l
