---
- name: Create 1Password rpm key directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  become: true
  loop:
    - /etc/pki/rpm-gpg
    - /etc/yum.repos.d

- name: Install 1Password rpm signing key
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/keys/1password.asc
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-1password
    mode: "0644"
  become: true

- name: Add 1Password rpm repository
  ansible.builtin.yum_repository:
    name: 1password
    file: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-1password
  become: true

- name: Install 1Password with dnf
  ansible.builtin.dnf:
    name:
      - 1password
      - 1password-cli
    state: present
  become: true
