[[native_updater]]
name = "none"

[[native_updater]]
name = "rpm-ostree"
commands = [["rpm-ostree", "upgrade"]]

[[native_updater]]
name = "pacman"
commands = [["sudo", "pacman", "-Syu"]]

[[native_updater]]
name = "dnf"
commands = [["sudo", "dnf", "upgrade", "-y"]]

[[native_updater]]
name = "apt"
commands = [
  ["sudo", "apt-get", "update"],
  ["sudo", "apt-get", "upgrade", "-y"],
]

[[opportunistic_updater]]
program = "flatpak"
commands = [["flatpak", "update", "-y"]]

[[opportunistic_updater]]
program = "brew"
commands = [
  ["brew", "update"],
  ["brew", "upgrade"],
]

[[os_release_updater]]
id = "arch"
updater = "pacman"

[[os_release_updater]]
id = "centos"
updater = "dnf"

[[os_release_updater]]
id = "debian"
updater = "apt"

[[os_release_updater]]
id = "fedora"
updater = "dnf"

[[os_release_updater]]
id = "rhel"
updater = "dnf"

[[os_release_updater]]
id = "ubuntu"
updater = "apt"
