[[language]]
name = "python"
auto-format = true
language-servers = ["ruff"]

[[language]]
name = "nix"
file-types = ["nix", { glob = "*.nix.tmpl" }]
auto-format = true
language-servers = ["nil-filtered"]

[[language]]
name = "bash"
file-types = [
  "sh",
  "bash",
  "zsh",
  { glob = "*.sh.tmpl" },
  { glob = "*.bash.tmpl" },
  { glob = "*.zsh.tmpl" },
  { glob = "dot_bash_profile.tmpl" },
  { glob = "dot_bashenv.tmpl" },
  { glob = "dot_bashrc.tmpl" },
  { glob = "dot_zshenv.tmpl" },
  { glob = "dot_zshrc.tmpl" },
]
auto-format = true
diagnostic-severity = "warning"
formatter = { command = "shfmt", args = ["-w"] }
language-servers = ["bash-language-server-filtered"]

[[language]]
name = "javascript"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["typescript-language-server"]

[[language]]
name = "css"
auto-format = true
language-servers = ["vscode-css-language-server"]

[[language]]
name = "json"
file-types = ["json", "jsonc", { glob = "*.json.tmpl" }]
auto-format = true
indent = { tab-width = 2, unit = "  " }
language-servers = ["vscode-json-language-server-filtered"]

[[language]]
name = "yaml"
file-types = ["yaml", "yml", { glob = "*.yaml.tmpl" }, { glob = "*.yml.tmpl" }]
auto-format = true
language-servers = ["yaml-language-server-filtered"]

[[language]]
name = "toml"
file-types = ["toml", { glob = "*.toml.tmpl" }, { glob = ".chezmoiexternal.toml.tmpl" }]
auto-format = true
language-servers = ["taplo-filtered"]

[language-server.bash-language-server-filtered]
command = "lsp-diagnostic-filter"
args = ["--", "bash-language-server", "start"]

[language-server.nil-filtered]
command = "lsp-diagnostic-filter"
args = ["--", "nil"]
[language-server.nil-filtered.config.nil.formatting]
command = ["nixfmt"]

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]
[language-server.ruff.config]
lineLength = 100
[language-server.ruff.config.lint]
extendSelect = ["I"]

[language-server.typescript-language-server]
command = "bunx"
args = ["--bun", "-p", "typescript-language-server", "typescript-language-server", "--stdio"]
[language-server.typescript-language-server.config]
hostInfo = "helix"

[language-server.vscode-css-language-server]
command = "bunx"
args = ["--bun", "-p", "vscode-langservers-extracted", "vscode-css-language-server", "--stdio"]

[language-server.vscode-json-language-server-filtered]
command = "lsp-diagnostic-filter"
args = [
  "--",
  "bunx",
  "--bun",
  "-p",
  "vscode-langservers-extracted",
  "vscode-json-language-server",
  "--stdio",
]

[language-server.yaml-language-server-filtered]
command = "lsp-diagnostic-filter"
args = ["--", "yaml-language-server", "--stdio"]
[language-server.yaml-language-server-filtered.config.yaml]
format = { enable = true }
validation = true
schemas = { https = true }

[language-server.taplo-filtered]
command = "lsp-diagnostic-filter"
args = ["--", "taplo", "lsp", "stdio"]
[language-server.taplo-filtered.config.formatter]
alignEntries = true
columnWidth = 100
