#!/usr/bin/env sh

[ "$(uname -s 2>/dev/null)" = "Darwin" ] || exit 0

exec zig run -lc \
  --dep chezmoi \
  -Mroot="$CHEZMOI_SOURCE_DIR/.chezmoi-lib/raycast_window_management/main.zig" \
  -Mchezmoi="$CHEZMOI_SOURCE_DIR/../lib/zig/chezmoi/script.zig" \
  -- "$@"
