[theme.dark]
name = "catppuccin-frappe-pink"
fg = "#c6d0f5"
bg = "#303446"

[theme.light]
name = "catppuccin-latte-pink"
fg = "#4c4f69"
bg = "#eff1f5"

[[probe_plan]]
os = "darwin"
fallback = "light"
commands = [
  ["defaults", "read", "-g", "AppleInterfaceStyle"],
]

[[probe_plan]]
os = "linux"
fallback = "dark"
commands = [
  ["gsettings", "get", "org.gnome.desktop.interface", "color-scheme"],
  ["gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"],
]

[[probe_plan]]
os = "freebsd"
fallback = "dark"
commands = [
  ["gsettings", "get", "org.gnome.desktop.interface", "color-scheme"],
  ["gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"],
]

[[probe_plan]]
os = "dragonfly"
fallback = "dark"
commands = [
  ["gsettings", "get", "org.gnome.desktop.interface", "color-scheme"],
  ["gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"],
]

[[probe_plan]]
os = "netbsd"
fallback = "dark"
commands = [
  ["gsettings", "get", "org.gnome.desktop.interface", "color-scheme"],
  ["gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"],
]

[[probe_plan]]
os = "openbsd"
fallback = "dark"
commands = [
  ["gsettings", "get", "org.gnome.desktop.interface", "color-scheme"],
  ["gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"],
]
