---
- name: Compose userland setup
  ansible.builtin.import_playbook: userland.yml
  tags:
    - userland

- name: Compose host-layer setup
  ansible.builtin.import_playbook: host.yml
  tags:
    - host
