---
- name: Install bootstrap packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - bootstrap
    - packages

- name: Install upstream bootstrap tools
  ansible.builtin.import_tasks: upstream-tools.yml
  tags:
    - bootstrap

- name: Configure Nix bootstrap
  ansible.builtin.import_tasks: nix.yml
  tags:
    - bootstrap
    - nix

- name: Run bootstrap migrations
  ansible.builtin.import_tasks: migrations.yml
  tags:
    - bootstrap
    - migration

- name: Install Go bootstrap
  ansible.builtin.import_tasks: go.yml
  tags:
    - bootstrap
    - go

- name: Install Rust bootstrap
  ansible.builtin.import_tasks: rustup.yml
  tags:
    - bootstrap
    - rustup
