chrome_store_update_url = "https://clients2.google.com/service/update2/crx"

[[chrome_store_extensions]]
id = "aeblfdkhhhdcdjpifhhbdiojplfjncoa"
name = "1Password"

[[chrome_store_extensions]]
id = "lnjaiaapbakfhlbjenjkhffcdpoompki"
name = "Catppuccin for Web File Explorer Icons"

[[chrome_store_extensions]]
id = "ponfpcnoihfmfllpaingbgckeeldkhle"
name = "Enhancer for YouTube"

[[chrome_store_extensions]]
id = "pobhoodpcipjmedfenaigbeloiidbflp"
name = "Minimal Theme for Twitter"

[[chrome_store_extensions]]
id = "ldgfbffkinooeloadekpmfoklnobpien"
name = "Raindrop"

[[chrome_store_extensions]]
id = "mnjggcdmjocbbbhaepdhchncahnbgone"
name = "SponsorBlock for YouTube"

[[chrome_store_extensions]]
id = "hlepfoohegkhhmjieoechaddaejaokhf"
name = "Refined GitHub"

[[update_url_extensions]]
id = "lkbebcjgcmobigpeffafkodonchffocl"
name = "Bypass Paywalls Clean"
update_url = "https://gitflic.ru/project/magnolia1234/bpc_updates/blob/raw?file=updates.xml"

[[crx_extensions]]
id = "bolggfoncklhniejomgplkjcllmnonbh"
name = "TWP - Translate Web Pages"
version = "10.1.1.0"
url = "https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v10.1.1.0/TWP_10.1.1.0_Chromium.crx"

[[zip_extensions]]
id = "hebmefdjnehapihcomeennjpdjghcpdn"
name = "Cookie AutoDelete"
version = "3.8.2"
url = "https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases/download/v3.8.2/Cookie-AutoDelete_v3.8.2_Chrome.zip"
load_unpacked = true
