[required.bootstrap]
packages = [
  "chezmoi",
  "curl",
  "direnv",
  "git",
  "git-lfs",
  "python3",
  "python3-libdnf5",
  "yamllint",
]

[required.toolchain]
packages = [
  "binutils",
  "clang",
  "cmake",
  "cargo",
  "gcc",
  "gcc-c++",
  "glibc-devel",
  "golang",
  "lld",
  "lldb",
  "make",
  "openssl-devel",
  "patch",
  "perl",
  "pkgconf-pkg-config",
  "rpm-build",
  "rustup",
  "zlib-devel",
]

[required.editors]
packages = [
  "code",
  "gh",
  "helix",
  "helix-parsers",
  "helix-themes",
  "nodejs",
  "nodejs-bash-language-server",
  "ShellCheck",
  "shfmt",
  "uv",
  "vim-enhanced",
]

[required.fonts]
packages = [
  "google-noto-color-emoji-fonts",
  "google-noto-emoji-fonts",
  "google-noto-sans-cjk-fonts",
  "google-noto-sans-mono-cjk-vf-fonts",
  "google-noto-sans-mono-vf-fonts",
  "google-noto-sans-symbols-2-fonts",
  "google-noto-sans-symbols-vf-fonts",
  "google-noto-sans-vf-fonts",
  "jetbrains-mono-fonts-all",
  "liberation-mono-fonts",
  "liberation-sans-fonts",
  "liberation-serif-fonts",
]

[required.terminal]
packages = [
  "age",
  "bat",
  "btop",
  "du-dust",
  "duf",
  "eza",
  "fd-find",
  "fzf",
  "git-delta",
  "git-filter-repo",
  "gitui",
  "gnupg2",
  "gnupg2-smime",
  "golangci-lint",
  "gopls",
  "hexyl",
  "hyperfine",
  "jq",
  "less",
  "lsof",
  "ncdu",
  "nmap",
  "nmap-ncat",
  "pass",
  "procs",
  "ripgrep",
  "ruff",
  "tldr",
  "tokei",
  "wget",
  "which",
  "wl-clipboard",
  "zoxide",
  "zsh",
]

[required.system]
packages = [
  "1password",
  "1password-cli",
  "bun",
  "ffmpeg",
  "file",
  "ghostty",
  "ImageMagick",
  "mediainfo",
  "opensc",
  "openssh-clients",
  "openssl",
  "pcsc-lite",
  "pinentry",
  "pinentry-gnome3",
  "podman",
  "podman-compose",
  "rar",
  "rsync",
  "selinux-policy-devel",
  "tailscale",
  "tree",
  "unzip",
  "xz",
  "zip",
]

[optional.terminal]
packages = [
  "bottom",
  "broot",
  "sd",
  "xh",
  "yazi",
  "zellij",
]
